version: "3.9"
services:
  db:
    image: nouchka/sqlite3:latest
    volumes:
      - ./data/db:/root/db
    environment:
      - SQLITE3_DB=db.sqlite3
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes: 
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

      #version: '3.9'
      #
      #services:
      #  web:
      #    build: ./app
      #    command: python manage.py runserver 0.0.0.0:8000
      #    volumes:
      #      - ./app/:/usr/src/app/
      #    ports:
      #      - 8000:8000
      #    env_file:
      #      - ./.env
      #    depends_on:
      #      - db
      #    links:
      #      - db:db
      #    networks:
      #      - djangonetwork
      #
      #  db:
      #    image: postgres:13.0-alpine
      #    volumes:
      #      - postgres_data:/var/lib/postgresql/data/
      #    environment:
      #      - POSTGRES_USER=postgres
      #      - POSTGRES_PASSWORD=postgres
      #      - POSTGRES_DB=capes
      #    networks:
      #      - djangonetwork
      #
      #  networks:
      #      djangonetwork:
      #          driver: bridge
      #volumes:
      #  postgres_data:
